---
- name: Flannel | Set Flannel etcd configuration
  command: |-
    {{ bin_dir }}/etcdctl --peers={{ etcd_access_addresses }} \
    set /{{ cluster_name }}/network/config \
    '{ "Network": "{{ kube_pods_subnet }}", "SubnetLen": {{ kube_network_node_prefix }}, "Backend": { "Type": "{{ flannel_backend_type }}" } }'
  delegate_to: "{{groups['etcd'][0]}}"
  run_once: true

- name: Flannel | Create flannel pod manifest
  template:
    src: flannel-pod.yml
    dest: /etc/kubernetes/manifests/flannel-pod.manifest
  notify: delete default docker bridge

- name: Flannel | Wait for flannel subnet.env file presence
  wait_for:
    path: /run/flannel/subnet.env
    delay: 5
    timeout: 600

- name: Flannel | Get flannel_subnet from subnet.env
  shell: cat /run/flannel/subnet.env | awk -F'=' '$1 == "FLANNEL_SUBNET" {print $2}'
  register: flannel_subnet_output
  changed_when: false

- set_fact:
    flannel_subnet: "{{ flannel_subnet_output.stdout }}"

- name: Flannel | Get flannel_mtu from subnet.env
  shell: cat /run/flannel/subnet.env | awk -F'=' '$1 == "FLANNEL_MTU" {print $2}'
  register: flannel_mtu_output
  changed_when: false

- set_fact:
    flannel_mtu: "{{ flannel_mtu_output.stdout }}"

- name: Flannel | Set docker daemon options
  template:
    src: docker
    dest: "/etc/default/docker"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart docker
  when: ansible_os_family != "CoreOS"

- name: Flannel | Create docker service path for CoreOS
  file: path=/etc/systemd/system/docker.service.d state=directory
  when: ansible_os_family == "CoreOS"

- name: Flannel | Create docker dropin for CoreOS
  template:
    src: docker-systemd
    dest: "/etc/systemd/system/docker.service.d/flannel-options.conf"
  notify:
    - restart docker
  when: ansible_os_family == "CoreOS"

- meta: flush_handlers
