---
- name: restart kubelet
  command: /bin/true
  notify:
    - Kubelet | reload systemd
    - Kubelet | reload kubelet

- name: Kubelet | reload systemd
  command: systemctl daemon-reload
  when: ansible_service_mgr == "systemd"

- name: Kubelet | reload kubelet
  service:
    name: kubelet
    state: restarted
