---
- name: restart calico-node
  command: /bin/true
  notify:
    - Calico | reload systemd
    - Calico | reload calico-node

- name : Calico | reload systemd
  shell: systemctl daemon-reload
  when: ansible_service_mgr == "systemd"

- name: Calico | reload calico-node
  service:
    name: calico-node
    state: restarted
    sleep: 10
