- name: Create canal ConfigMap
  run_once: true
  kube:
    name: "canal-config"
    kubectl: "{{bin_dir}}/kubectl"
    filename: "/etc/kubernetes/canal-config.yaml"
    resource: "configmap"
    namespace: "kube-system"

- name: Start flannel and calico-node
  run_once: true
  kube:
    name: "canal-node"
    kubectl: "{{bin_dir}}/kubectl"
    filename: "/etc/kubernetes/canal-node.yaml"
    resource: "ds"
    namespace: "kube-system"
