---
- name: delete default docker bridge
  command: ip link delete docker0
  ignore_errors: yes
  notify: restart docker

- name: Flannel | reload kubelet
  service:
    name: kubelet
    state: restarted
