# This is where all the cert scripts and certs will be located
kube_cert_dir: "{{ kube_config_dir }}/ssl"

# change to 0.0.0.0 to enable insecure access from anywhere (not recommended)
kube_apiserver_insecure_bind_address: 127.0.0.1

# This is where you can drop yaml/json files and the kubelet will run those
# pods on startup
kube_manifest_dir: "{{ kube_config_dir }}/manifests"

dns_domain: "{{ cluster_name }}"

# resolv.conf to base dns config
kube_resolv_conf: "/etc/resolv.conf"

kube_proxy_mode: iptables

# If using the pure iptables proxy, SNAT everything
kube_proxy_masquerade_all: true

# kube_api_runtime_config:
#   - extensions/v1beta1/daemonsets=true
#   - extensions/v1beta1/deployments=true

# Logging directory (sysvinit systems)
kube_log_dir: "/var/log/kubernetes"

# This directory is where all the additional config stuff goes
# the kubernetes normally puts in /srv/kubernets.
# This puts them in a sane location.
# Editting this value will almost surely break something. Don't
# change it. Things like the systemd scripts are hard coded to
# look in here. Don't do it.
kube_config_dir: /etc/kubernetes

nginx_image_repo: nginx
nginx_image_tag: 1.11.4-alpine
