# The interface used by canal for host <-> host communication.
# If left blank, then the interface is chosing using the node's
# default route.
canal_iface: ""

# Whether or not to masquerade traffic to destinations not within
# the pod network.
canal_masquerade: "true"

# Log-level
canal_log_level: "info"

# Etcd SSL dirs
canal_cert_dir: /etc/canal/certs
etcd_cert_dir: /etc/ssl/etcd/ssl
